FROM almalinux:9
RUN mkdir /tmp/docker
# RUN cd /tmp/docker  # in docker there is no concept called cd for this we use workdir
WORKDIR /tmp/docker
RUN pwd
RUN echo "Hello, This is HemanthKumar" > sample.txt
